year: 2022
kickoff_date: "2022-11-20"
actual_champion: Argentina
groups:
  A: [Qatar, Ecuador, Senegal, Netherlands]
  B: [England, Iran, United States, Wales]
  C: [Argentina, Saudi Arabia, Mexico, Poland]
  D: [France, Australia, Denmark, Tunisia]
  E: [Spain, Costa Rica, Germany, Japan]
  F: [Belgium, Canada, Morocco, Croatia]
  G: [Brazil, Serbia, Switzerland, Cameroon]
  H: [Portugal, Ghana, Uruguay, South Korea]
